### ISSUE TITLE
Proposals: Introduce a formatter

### ISSUE THREAD

**Issue by junkmd** [enthought/comtypes#418]
I would like to introduce a formatter for codebases in statically defined modules.

I would like to be able to apply a formatter to PRed codebases by GitHub Actions.
I have wanted to introduce it, but was concerned that it would break the old Python syntax.
But on the `drop_py2` plan and its branch, that fear is removed.

Keep in mind, I do not intend to apply this to modules under `comtypes.gen` that are dynamically generated.
Because it would require third-party libraries for runtime dependencies, which goes against the "pure python" intent of this library.
- As much as possible, the `codegenerator` process should be able to generate readable code.
However, if the code generation process itself becomes more complicated because of this, I do not mind if the generated code is a little difficult to read.

**Comment by junkmd** [comment]
@cfarrow 
@jaraco 
@vasily-v-ryabov 
And other community participants

I recommend [`black`](https://pypi.org/project/black/).

GHA setting will be follows.
```
# .../.github/workflows/autofmt.yml
on:
  push:

jobs:
    formatter:
        name: formatter
        runs-on: windows-latest
        strategy:
            matrix:
                python-version: [3.7]
        steps:
          - name: Checkout
            uses: actions/checkout@v3
          - name: Set up Python ${{ matrix.python-version }}
            uses: actions/setup-python@v4
            with:
              python-version: ${{ matrix.python-version }}
          - name: Install black
            run: pip install black==22.12.0
          - name: black
            run: python -m black .
          - uses: stefanzweifel/git-auto-commit-action@v4
            with:
              commit_message: Apply Code Formatter Change
              ref: ${{ github.head_ref }}

```

`black` has fewer settings than other formatters. Thus, there should be less community exhaustion by having to tussle with setting values.

Almost the only debatable setting value would be `line_length`.
The default value for black is [88 characters](https://black.readthedocs.io/en/stable/the_black_code_style/current_style.html#line-length).

I looked at how some well-known projects set theirs up.

- [`typeshed`](https://github.com/python/typeshed/blob/8671fc5c0f1a5f06ebc0e43c10eddd6714e41d7d/pyproject.toml#L1-L8)
- [`pipenv`](https://github.com/pypa/pipenv/blob/cff5620a478249f487064d5fcd8674978ac6d683/pyproject.toml#L5-L30)
- [`django`](https://github.com/django/django/blob/0bd2c0c9015b53c41394a1c0989afbfd94dc2830/pyproject.toml#L5-L7)
- [`pandas`](https://github.com/pandas-dev/pandas/blob/2e1206e112f126c7c8508cba44b5b7975e24ca91/pyproject.toml#L167-L185)
- [`attrs`](https://github.com/python-attrs/attrs/blob/88d2a377487effdac54acdedf1d7d6c400f002e5/pyproject.toml#L33-L34)

Some of them are quite long, like `typeshed` at 130, some are a little longer, like `pipenv` at 90, some are unchanged from the default, like `django` and `pandas`, and some are 79 to be PEP8-compliant, like `attrs`.

I am considering not changing the set values from the defaults to avoid controversy.

Any opinion would be appreciated.
If there is no objections, I intend to introduce this by the end of this year.

**Comment by junkmd** [comment]
I tried it with my fork.
https://github.com/enthought/comtypes/compare/14ae44dcb33c727605bb3a72f4f0e929328b2296...9baccaad51522ce5bc310ddb2a9c86ea9acb4957

Since `__all__` and `__known_symbols__` would be redundant, they would need `fmt: off`.

**Comment by junkmd** [comment]
GHA settings is improved.

```yml
on:
  pull_request:
    branches: [drop_py2]  # TODO: add master(main)

jobs:
    formatter:
        name: formatter
        runs-on: windows-latest
        strategy:
            matrix:
                python-version: [3.7]
        steps:
          - name: Checkout
            uses: actions/checkout@v3
          - name: Set up Python ${{ matrix.python-version }}
            uses: actions/setup-python@v4
            with:
              python-version: ${{ matrix.python-version }}
          - name: Install black
            run: pip install black==22.12.0
          - name: format
            run: python -m black .
          - uses: stefanzweifel/git-auto-commit-action@v4
            with:
              commit_message: apply code formatter change
              commit_user_name: github-actions[bot]
              commit_user_email: 41898282+github-actions[bot]@users.noreply.github.com
              commit_author: github-actions[bot] <41898282+github-actions[bot]@users.noreply.github.com>
              branch: ${{ github.head_ref }}

```

- Since it was redundant to trigger on every `push`, so I made it on every `pull_request`.
- I made it explicit that both the committer and the author should be github bot.

I have experimented with this.

https://github.com/enthought/comtypes/compare/1398608e5cd1352f80e5962077c1179991dca945...730905502682f5853bbf9f99b1d08f5468569b18
